# Generated by Django 5.0.8 on 2024-08-08 15:03

import bot.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(upload_to=bot.models.base_model.PathAndRename('bot/competition/images/')),
        ),
    ]
