# Generated by Django 5.0.8 on 2024-08-08 15:10

import bot.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_sportstype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='stream_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sportstype',
            name='image',
            field=models.ImageField(upload_to=bot.models.base_model.PathAndRename('bot/sport_type/images/')),
        ),
    ]
