# Generated by Django 5.0.8 on 2024-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_competition_stream_link_alter_sportstype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='send_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='send_channel',
            field=models.BooleanField(default=False),
        ),
    ]
