# Generated by Django 5.0.8 on 2024-08-11 11:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_competition_send_bot_competition_send_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
