# Generated by Django 5.0.8 on 2024-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_competition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
