# Generated by Django 5.0.8 on 2024-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_competition_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstype',
            name='file_id',
            field=models.CharField(blank=True, help_text="To'ldirilishi shart emas!!! Server tomonidan amalga oshiriladi", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='file_id',
            field=models.CharField(blank=True, help_text="Bu maydon to'dirilishi shart emas server tomondan qo'ldiriladi", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='stream_link',
            field=models.URLField(blank=True, help_text="Steam boshlanganda havolani qo'shing", max_length=255, null=True),
        ),
    ]
