# Generated by Django 5.0.8 on 2024-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_sportstype_file_id_alter_competition_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
