# Generated by Django 5.0.8 on 2024-08-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_user_chat_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
