# Generated by Django 5.0.8 on 2024-08-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blocked',
            new_name='active',
        ),
    ]
