# Generated by Django 5.0.8 on 2024-08-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_rename_blocked_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
