# Generated by Django 5.0.8 on 2024-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='channels',
            field=models.ManyToManyField(blank=True, null=True, to='bot.channel'),
        ),
    ]
